## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

BACKGROUND = #282a36
FOREGROUND = #f8f8f2
ALTBACKGROUND = #44475a
ALTFOREGROUND = #6272a4
ACCENT = #bd93f9

BLACK = #282a36
RED = #ff5555
GREEN = #50fa7b
YELLOW = #f1fa8c
BLUE = #8be9fd
MAGENTA = #ff79c6
CYAN = #8be9fd
WHITE = #f8f8f2
ALTBLACK = #44475a
ALTRED = #ff5555
ALTGREEN = #50fa7b
ALTYELLOW = #f1fa8c
ALTBLUE = #8be9fd
ALTMAGENTA = #ff79c6
ALTCYAN = #8be9fd
ALTWHITE = #bfbfbf
